
# Bullseye debian 11 --> Penultimate stable
# Bookworm debian 12 --> Stable
# Trixie   debian 13 --> Testing

FROM debian:bullseye

WORKDIR /app

RUN apt-get update && apt-get install -y wordpress

CMD []