user www-data;
worker_processes auto;
pid /run/nginx.pid;

events {
	worker_connections 1024;
}

http {
	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	server {
		listen 8080;
		server_name tarini.42.fr;
		root /var/www/status;
		index index.html;

		location / {
			try_files $uri $uri/ =404;
		}

		location /status.json {
			alias /var/www/status/status.json;
			add_header Content-Type application/json;
			add_header Cache-Control "no-cache";
		}
	}
}